server:
  port: 8082
  servlet:
    context-path: /

#=========================================  redis 配置  ======================================================#
spring:
  redis:
    host: 114.115.181.119
    port: 6379
    timeout: 0