server:
  port: 8082
  servlet:
    context-path: /

#=========================================  redis 配置  ======================================================#
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0